"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowDown, Play, Plus, Minus, X, Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import initialMetrics from "@/public/data/metrics.json";
import { Silk } from "./silk";
import {validMetrics} from "@/lib/metrics";
const img=(n:string)=>`/assets/images/${n}.webp`;
const whatsapp="https://wa.me/5548998170835?text=Ol%C3%A1%2C%20Tainara!%20Gostaria%20de%20conversar%20sobre%20um%20projeto%20para%20minha%20marca.";
const works=[
{title:"O produto em primeiro plano",category:"Haircare · UGC",file:"cuidados-cabelo-ugc-v2",desc:"Textura, movimento e demonstração de cuidados com o cabelo."},
{title:"Um novo olhar",category:"Eyewear · Visual Ótica Joalheria",file:"otica-visual-conteudo",desc:"Óculos e presença de câmera em conteúdo produzido para a marca."},
{title:"Histórias que aproximam",category:"Joias · Lifestyle",file:"joias-estilo",desc:"Joias e afeto em uma narrativa visual de casal."},
{title:"Experiência de produto",category:"Gastronomia · UGC",file:"product-experience",desc:"Produto inserido em uma experiência cotidiana."},
{title:"Conversa de verdade",category:"Fala direta · Conteúdo comercial",file:"talking-head-ad",desc:"Apresentação de serviço com fala direta à câmera."},
{title:"Momentos a dois",category:"Casal · Lifestyle",file:"couple-lifestyle",desc:"Conteúdo de casal com linguagem espontânea."},
{title:"Uma receita, uma história",category:"Rotina · Gastronomia",file:"rotina-gastronomia-portfolio",poster:"rotina-gastronomia",desc:"Receita e fala direta em uma rotina real."}];
const gallery=[
["nova-01-moda-urbana","Moda urbana","Tainara atravessando a rua em produção preta"],
["beauty-lips","Beauty","Tainara aplicando produto labial diante do espelho"],
["nova-13-cafe-editorial","Lifestyle","Tainara com uma xícara em um café"],
["fashion-pink","Fashion","Tainara em ensaio de moda com camisa rosa"],
["nova-07-oculos-close","Eyewear","Retrato de Tainara usando óculos escuros"],
["nova-16-criacao-estudio","Bastidores","Tainara produzindo conteúdo em estúdio"],
["lifestyle-wine","Autocuidado","Tainara em produção vinho em ambiente interno"],
["nova-12-oculos-duplo","Acessórios","Tainara apresentando dois modelos de óculos"],
["nova-09-lifestyle-cafe","Lifestyle","Tainara sorrindo na entrada de um café"],
["eyewear-light","Óculos","Tainara usando óculos de armação clara em estúdio"],
["nova-08-lifestyle-notebook","Cotidiano","Tainara trabalhando com notebook em uma cafeteria"],
["nova-17-retrato-sorrindo","Retrato","Retrato de Tainara sorrindo"],
["nova-10-lifestyle-vermelho","Lifestyle","Tainara de camisa vermelha usando um celular"],
["behind-scenes-1","Estúdio","Tainara sentada em estúdio usando conjunto preto"]];
type Media={type:"video"|"image";src:string;title:string;desc:string;poster?:string};
const nf=new Intl.NumberFormat("pt-BR");const compact=(n:number)=>nf.format(n/1000)+" mil";
function Label({n,children}:{n:string;children:React.ReactNode}){return <div className="section-label"><span>{n}</span>{children}</div>}
function CTA({children="Vamos criar juntos"}:{children?:React.ReactNode}){return <Button asChild className="cta"><a href={whatsapp} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={18}/></a></Button>}
export default function Home(){
 const [menu,setMenu]=useState(false),[moreWorks,setMoreWorks]=useState(false),[morePhotos,setMorePhotos]=useState(false),[media,setMedia]=useState<Media|null>(null),[metrics,setMetrics]=useState(initialMetrics);
 const lastTrigger=useRef<HTMLElement|null>(null),videoRef=useRef<HTMLVideoElement>(null);
 function openMedia(v:Media){lastTrigger.current=document.activeElement as HTMLElement;setMedia(v)}
 function openVideo(w:typeof works[number]){openMedia({type:"video",src:`/assets/videos/${w.file}.mp4`,poster:`/assets/posters/${w.poster||w.file}.jpg`,title:w.title,desc:w.desc})}
 useEffect(()=>{const abort=new AbortController();if(location.protocol!=="file:")fetch("/data/metrics.json",{cache:"no-cache",signal:abort.signal}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(validMetrics(d))setMetrics(d)}).catch(()=>{});
 const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("seen");observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>observer.observe(e));const pause=()=>{if(document.hidden)videoRef.current?.pause()};document.addEventListener("visibilitychange",pause);return()=>{abort.abort();observer.disconnect();document.removeEventListener("visibilitychange",pause)}},[]);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setMenu(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[menu]);
 const ig=metrics.instagram,tt=metrics.tiktok;const period=(a:string,b:string)=>`${a.slice(8)}/${a.slice(5,7)} a ${b.slice(8)}/${b.slice(5,7)}/${b.slice(0,4)}`;
 return <><a className="skip" href="#conteudo">Ir para o conteúdo</a>
 <header className="nav-wrap"><nav className="nav shell" aria-label="Navegação principal"><a className="wordmark" href="#inicio" aria-label="Tainara Demarch, início">tainara<span>demarch</span></a><div className={`nav-links ${menu?"is-open":""}`} id="navigation">{[["Trabalhos","trabalhos"],["Sobre","sobre"],["Audiência","audiencia"],["Contato","contato"]].map(([t,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{t}</a>)}</div><a className="nav-project" href={whatsapp} target="_blank" rel="noopener noreferrer">Vamos conversar <ArrowUpRight size={16}/></a><Button variant="ghost" className="menu-toggle" aria-label={menu?"Fechar menu":"Abrir menu"} aria-controls="navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></nav></header>
 <main id="conteudo"><section className="hero shell" id="inicio"><div className="hero-copy"><p className="eyebrow">CRIADORA DE CONTEÚDO & MODELO COMERCIAL</p><h1>Tainara<br/><em>Demarch.</em></h1><div className="hero-line"/><p className="hero-statement">Presença que marca.<br/>Conteúdo que aproxima.</p><p className="hero-description">Naturalidade de creator. Olhar de modelo.<br/>Uma presença autêntica para a sua marca.</p><div className="hero-actions"><CTA/><a href="#trabalhos" className="text-link">Explore o portfólio <ArrowDown size={16}/></a></div><div className="hero-foot"><span>UGC · MODA · BELEZA · LIFESTYLE</span><span>SC, BRASIL</span></div></div><div className="hero-visual"><img className="hero-photo" src={img("portrait-hero")} alt="Tainara Demarch em retrato editorial, de óculos e cabelos cacheados" fetchPriority="high" width="900" height="1200"/><Silk/><span className="image-index">PORTFÓLIO / 2026</span><button className="reel-teaser" onClick={()=>openMedia({type:"video",src:"/assets/videos/video-apresentacao.mp4",poster:"/assets/posters/video-apresentacao.jpg",title:"Conheça meu trabalho",desc:"Apresentação em vídeo · Tainara Demarch"})}><span className="play-disc"><Play size={18} fill="currentColor"/></span><span>Presença em movimento<small>ASSISTIR APRESENTAÇÃO · 24 S</small></span></button></div></section>
 <div className="specialties"><div className="shell"><span>BEAUTY</span><i>✳</i><span>FASHION</span><i>✳</i><span>SKINCARE</span><i>✳</i><span>HAIRCARE</span><i>✳</i><span>LIFESTYLE</span></div></div>
 <section className="selected shell section" id="trabalhos"><div className="section-head reveal"><div><Label n="01">TRABALHOS SELECIONADOS</Label><h2>Feito para ser <em>sentido.</em></h2></div><p>Texturas, gestos e histórias.<br/>O universo da marca encontra a vida real.</p></div><div className="work-grid">{works.slice(0,moreWorks?works.length:3).map((w,i)=><article className="work" key={w.file}><button className="work-image" onClick={()=>openVideo(w)} aria-label={`Assistir: ${w.title}`}><img src={`/assets/posters/${w.poster||w.file}.jpg`} alt={w.desc} loading="lazy" width="720" height="1280"/><span className="work-number">0{i+1}</span><span className="play-disc"><Play size={20} fill="currentColor"/></span><span className="watch-label">ASSISTIR FILME</span></button><div className="work-caption"><div><p>{w.category}</p><h3>{w.title}</h3></div><ArrowUpRight size={20}/></div></article>)}</div><Button variant="outline" className="expand" aria-expanded={moreWorks} onClick={()=>setMoreWorks(!moreWorks)}>{moreWorks?"Mostrar seleção":"Ver todos os trabalhos"}{moreWorks?<Minus size={17}/>:<Plus size={17}/>}</Button></section>
 <section className="about section" id="sobre"><div className="shell about-grid"><div className="about-photo reveal"><img src={img("capa-tainara-demarch")} alt="Tainara em seu ambiente de criação, com celular e iluminação de estúdio" loading="lazy" width="800" height="1000"/><span className="photo-caption">CRIATIVIDADE, DO MEU OLHAR AO SEU PROJETO.</span></div><div className="about-copy reveal"><Label n="02">POR TRÁS DO CONTEÚDO</Label><h2>Olhar de modelo.<br/><em>Essência de creator.</em></h2><p className="lead">Sou Tainara. Uno experiência diante das câmeras à naturalidade de quem gosta de contar histórias.</p><p>Minha trajetória como modelo comercial trouxe consciência de luz, movimento e composição. Na criação de conteúdo, esse olhar encontra a conversa próxima, a rotina e os detalhes que tornam um produto parte da vida.</p><p>Crio para marcas de beleza, moda e lifestyle, com espaço para joias, acessórios, autocuidado, casa, pet e experiências de viagem, hotelaria, gastronomia e casal.</p><div className="experience"><span>EXPERIÊNCIA COMO MODELO COMERCIAL</span><div>Vuk Jeans <i>/</i> Charlott</div><small>Trabalhos anteriores como modelo comercial.</small></div><p className="location">Araranguá, Santa Catarina · Projetos em todo o Brasil</p></div></div></section>
 <section className="brand-story shell section" id="visual"><div className="story-copy reveal"><Label n="03">CONTEÚDO COM CONTINUIDADE</Label><h2>Um olhar.<br/><em>Muitas histórias.</em></h2><h3>Visual Ótica Joalheria</h3><p>Produção recorrente de conteúdo para a marca, explorando óculos, joias e acessórios em diferentes cenas e linguagens.</p><p>Presença de câmera, atenção ao produto e familiaridade com a identidade da marca a cada nova produção.</p><Button variant="outline" className="expand" onClick={()=>openVideo(works[1])}>Ver o conteúdo <Play size={15}/></Button></div><div className="story-photos reveal"><img src={img("nova-05-otica-jornal")} alt="Tainara com jornal da Visual Ótica Joalheria" loading="lazy" width="700" height="1000"/><img src={img("nova-04-otica-cafe")} alt="Tainara usando óculos de grau em uma cafeteria" loading="lazy" width="600" height="850"/><span>PRODUTO EM CENA. PERSONALIDADE PRESENTE.</span></div></section>
 <section className="audience section" id="audiencia"><div className="shell"><div className="section-head reveal"><div><Label n="04">PRESENÇA DIGITAL</Label><h2>Conexões reais.<br/><em>Uma audiência presente.</em></h2></div><p>Além do conteúdo para a sua marca,<br/>uma comunidade para conversar com ela.</p></div><div className="platform-head"><a href="https://instagram.com/tainarademarch" target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={17}/></a><span>{period(ig.period_start,ig.period_end)} · 30 dias</span></div><div className="stats">{[[nf.format(ig.followers),"Seguidores"],[compact(ig.views_30d),"Visualizações · 30 dias"],[nf.format(ig.interactions_30d),"Interações · 30 dias"],[nf.format(ig.women_pct)+"%","Audiência feminina"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><div className="audience-bottom"><div className="audience-profile"><p className="eyebrow">QUEM ACOMPANHA NO INSTAGRAM</p><p><strong>{nf.format(ig.age_25_44_pct)}%</strong> entre 25 e 44 anos.<br/><strong>{nf.format(ig.brazil_pct)}%</strong> no Brasil.</p><details><summary>Mais sobre a audiência <Plus size={14}/></summary><div className="age-list">{Object.entries(ig.age_distribution).map(([age,v])=><div key={age}><span>{age} anos</span><span>{nf.format(v)}%</span></div>)}</div></details></div><div className="tiktok"><div className="platform-head"><a href="https://www.tiktok.com/@tainara.demarch" target="_blank" rel="noopener noreferrer">TikTok <ArrowUpRight size={17}/></a><span>{period(tt.period_start,tt.period_end)} · 7 dias</span></div><div className="tiktok-stats">{[[nf.format(tt.followers),"Seguidores"],[compact(tt.post_views_7d),"Visualizações · 7 dias"],[compact(tt.viewers_7d),"Espectadores · 7 dias"],["+"+compact(tt.net_followers_7d),"Seguidores líquidos · 7 dias"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div></div></div><p className="metrics-note">Fonte: capturas dos Insights do Instagram e TikTok fornecidas em {metrics.updated_at.split("-").reverse().join("/")}. Valores arredondados conforme os painéis. Retrato dos períodos indicados.</p></div></section>
 <section className="gallery shell section" id="galeria"><div className="section-head reveal"><div><Label n="05">PORTFÓLIO FOTOGRÁFICO</Label><h2>Entre a cena <em>e o instante.</em></h2></div><p>Moda. Beleza. Vida acontecendo.</p></div><div className="photo-grid">{gallery.slice(0,morePhotos?gallery.length:6).map(([file,title,alt],i)=><button key={file} className={`gallery-item item-${i%6}`} aria-label={`Ampliar: ${title}`} onClick={()=>openMedia({type:"image",src:img(file),title,desc:alt})}><img src={img(file)} alt={alt} loading="lazy" width="700" height="1000"/><span>{title}<Plus size={18}/></span></button>)}</div><Button variant="outline" className="expand" aria-expanded={morePhotos} onClick={()=>setMorePhotos(!morePhotos)}>{morePhotos?"Mostrar seleção":"Explorar a galeria"}{morePhotos?<Minus size={17}/>:<Plus size={17}/>}</Button></section>
 <section className="services section" id="servicos"><div className="shell services-grid"><div className="reveal"><Label n="06">COMO PODEMOS CRIAR</Label><h2>A sua marca.<br/><em>Novas possibilidades.</em></h2><p>Da ideia à imagem final, uma criação alinhada ao que a sua marca quer comunicar.</p></div><div className="service-list">{[["01","UGC & redes sociais","Demonstração, review, unboxing, tutorial e fala direta. Reels, TikTok, rotina e locução com linguagem natural."],["02","Modelo comercial","Campanhas, catálogos, editoriais, fotografia e vídeo comercial. Presença de câmera a serviço da direção criativa."],["03","Produção criativa","Conceito, roteiro, captação, edição e legendas. Conteúdo orgânico e peças para anúncios conforme o briefing."],["04","Presença digital","Projetos com publicação no Instagram e TikTok, aproximando a marca da audiência dos meus perfis."]].map(([n,t,d])=><details key={n}><summary><span>{n}</span><h3>{t}</h3><Plus size={20}/></summary><p>{d}</p></details>)}<p className="service-note">Direitos de uso, mídia paga, exclusividade, prazos e revisões são definidos na proposta de cada projeto.</p></div></div></section>
 <section className="process shell section"><div className="section-head"><div><Label n="07">DO PRIMEIRO CONTATO À ENTREGA</Label><h2>Clareza em <em>cada etapa.</em></h2></div></div><div className="process-grid">{[["01","Escuta","Briefing, objetivo, público e referências da marca."],["02","Ideia","Conceito, roteiro e linguagem pensados para o projeto."],["03","Criação","Captação, fotografia e edição conforme o escopo."],["04","Entrega","Materiais nos formatos, prazos e condições combinados."]].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
 <section className="contact section" id="contato"><div className="shell contact-grid"><div><Label n="08">MARCAS, AGÊNCIAS & BOAS IDEIAS</Label><h2>Vamos criar<br/><em>algo com presença?</em></h2><p>Me conte sobre a sua marca.<br/>A próxima história pode ser nossa.</p><CTA>Conversar sobre um projeto</CTA></div><div className="contact-aside"><a href="mailto:tainarademarchugc@gmail.com">tainarademarchugc@gmail.com <ArrowUpRight size={18}/></a><a href="https://instagram.com/tainarademarch" target="_blank" rel="noopener noreferrer">Instagram · @tainarademarch <ArrowUpRight size={18}/></a><a href="https://www.tiktok.com/@tainara.demarch" target="_blank" rel="noopener noreferrer">TikTok · @tainara.demarch <ArrowUpRight size={18}/></a><a href="/assets/docs/midia-kit-tainara-demarch.pdf" target="_blank" rel="noopener noreferrer">Mídia kit · edição original <ArrowUpRight size={18}/></a><small>Para métricas atualizadas, consulte os períodos neste portfólio.</small></div></div></section></main>
 <footer className="shell footer"><a className="wordmark" href="#inicio">tainara<span>demarch</span></a><p>Criadora de conteúdo · Modelo comercial · UGC</p><span>Araranguá, SC · Brasil</span></footer>
 <Dialog open={!!media} onOpenChange={o=>{if(!o)setMedia(null)}}><DialogContent className="media-dialog" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();lastTrigger.current?.focus()}}><DialogClose className="media-close" aria-label="Fechar visualização"><X size={22}/></DialogClose><DialogTitle>{media?.title}</DialogTitle><DialogDescription>{media?.desc}</DialogDescription>{media?.type==="video"?<video ref={videoRef} key={media.src} src={media.src} poster={media.poster} controls playsInline preload="metadata"/>:media&&<img src={media.src} alt={media.desc}/>} {media?.type==="video"&&<a className="video-direct" href={media.src} target="_blank" rel="noopener noreferrer">Abrir vídeo diretamente <ArrowUpRight size={14}/></a>}</DialogContent></Dialog>
 </>;
}
