"use client";
import {useEffect,useRef} from 'react';
// A low-resolution additive light layer. Never samples or warps the portrait.
export function Silk(){const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=canvas.current;if(!c)return;const mq=matchMedia('(prefers-reduced-motion: reduce)');const small=matchMedia('(max-width: 760px)').matches;const memory=(navigator as Navigator & {deviceMemory?:number}).deviceMemory;const connection=(navigator as Navigator & {connection?:{saveData?:boolean}}).connection;if(mq.matches||connection?.saveData||(memory&&memory<4))return;
 const gl=c.getContext('webgl',{alpha:true,antialias:false,powerPreference:'low-power',premultipliedAlpha:false});if(!gl)return;const shaders:WebGLShader[]=[];
 function compile(type:number,src:string){const s=gl!.createShader(type)!;gl!.shaderSource(s,src);gl!.compileShader(s);if(!gl!.getShaderParameter(s,gl!.COMPILE_STATUS)){gl!.deleteShader(s);return null}shaders.push(s);return s}
 const vs=compile(gl.VERTEX_SHADER,'attribute vec2 p; varying vec2 uv; void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}');
 const fs=compile(gl.FRAGMENT_SHADER,`precision mediump float; varying vec2 uv; uniform float time; uniform vec2 mouse; void main(){vec2 q=uv; float bend=sin(q.y*4.8+time*.18)*.17+sin(q.y*9.-time*.12)*.025;float wave=q.x+bend+mouse.x*.022;float silk=pow(.5+.5*sin(wave*14.+time*.12),10.);float fine=pow(.5+.5*sin(wave*27.-time*.09),22.)*.3;float faceMask=smoothstep(.12,.48,abs(q.x-.5))*.7+.15;float grain=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453)*.017;vec3 pearl=mix(vec3(.67,.48,.42),vec3(.96,.9,.81),q.y);gl_FragColor=vec4(pearl*(silk+fine+grain),faceMask*.64);}`);
 if(!vs||!fs){shaders.forEach(s=>gl.deleteShader(s));return}const program=gl.createProgram()!;gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){gl.deleteProgram(program);shaders.forEach(s=>gl.deleteShader(s));return}gl.useProgram(program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const ut=gl.getUniformLocation(program,'time'),um=gl.getUniformLocation(program,'mouse');
 let raf=0,inView=true,lost=false,last=0,elapsed=0,mx=0,my=0;const resize=()=>{const r=c.getBoundingClientRect();const dpr=Math.min(devicePixelRatio,small?.65:1);c.width=Math.max(1,Math.round(r.width*dpr));c.height=Math.max(1,Math.round(r.height*dpr));gl.viewport(0,0,c.width,c.height)};resize();const ro=new ResizeObserver(resize);ro.observe(c);
 const draw=(now:number)=>{raf=0;if(document.hidden||!inView||lost||mq.matches)return;if(now-last>=(small?66:33)){elapsed+=Math.min((now-last)/1000,.1);last=now;gl.uniform1f(ut,elapsed);gl.uniform2f(um,mx,my);gl.drawArrays(gl.TRIANGLES,0,6)}raf=requestAnimationFrame(draw)};const sync=()=>{if(raf)cancelAnimationFrame(raf);raf=0;if(!document.hidden&&inView&&!lost&&!mq.matches){last=performance.now();raf=requestAnimationFrame(draw)}};const observer=new IntersectionObserver(es=>{inView=es[0].isIntersecting;sync()});observer.observe(c);const move=(e:PointerEvent)=>{const r=c.getBoundingClientRect();mx=(e.clientX-r.left)/r.width-.5;my=(e.clientY-r.top)/r.height-.5};const contextLost=()=>{lost=true;c.style.opacity='0';sync()};c.addEventListener('webglcontextlost',contextLost);c.parentElement?.addEventListener('pointermove',move);document.addEventListener('visibilitychange',sync);mq.addEventListener('change',sync);sync();return()=>{cancelAnimationFrame(raf);observer.disconnect();ro.disconnect();document.removeEventListener('visibilitychange',sync);mq.removeEventListener('change',sync);c.removeEventListener('webglcontextlost',contextLost);c.parentElement?.removeEventListener('pointermove',move);gl.deleteBuffer(b);gl.deleteProgram(program);shaders.forEach(s=>gl.deleteShader(s))};},[]);return <canvas ref={canvas} className="silk-canvas" aria-hidden="true"/>}
